---
# handlers file for nginx
- name: nginx restart service
  systemd:
      name: nginx
      state: restarted
      daemon_reload: yes

- name: start nginx
  systemd:
    name: nginx
    enable: yes
    state: started

- name: nginx reload service
  systemd:
    name: nginx
    daemon_reload: yes
